<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Halte extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Halte_model');
    } 

    /*
     * Listing of halte
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('halte/index?');
        $config['total_rows'] = $this->Halte_model->get_all_halte_count();
        $this->pagination->initialize($config);

        $data['halte'] = $this->Halte_model->get_all_halte($params);
        
        $data['_view'] = 'halte/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new halte
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required');
		$this->form_validation->set_rules('longtitude','Longtitude','required');
		$this->form_validation->set_rules('langtitude','Langtitude','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
				'longtitude' => $this->input->post('longtitude'),
				'langtitude' => $this->input->post('langtitude'),
				'icon' => $this->input->post('icon'),
				'gambar' => $this->input->post('gambar'),
            );
            
            $halte_id = $this->Halte_model->add_halte($params);
            redirect('halte/index');
        }
        else
        {            
            $data['_view'] = 'halte/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a halte
     */
    function edit($id)
    {   
        // check if the halte exists before trying to edit it
        $data['halte'] = $this->Halte_model->get_halte($id);
        
        if(isset($data['halte']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required');
			$this->form_validation->set_rules('longtitude','Longtitude','required');
			$this->form_validation->set_rules('langtitude','Langtitude','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
					'longtitude' => $this->input->post('longtitude'),
					'langtitude' => $this->input->post('langtitude'),
					'icon' => $this->input->post('icon'),
					'gambar' => $this->input->post('gambar'),
                );

                $this->Halte_model->update_halte($id,$params);            
                redirect('halte/index');
            }
            else
            {
                $data['_view'] = 'halte/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The halte you are trying to edit does not exist.');
    } 

    /*
     * Deleting halte
     */
    function remove($id)
    {
        $halte = $this->Halte_model->get_halte($id);

        // check if the halte exists before trying to delete it
        if(isset($halte['id']))
        {
            $this->Halte_model->delete_halte($id);
            redirect('halte/index');
        }
        else
            show_error('The halte you are trying to delete does not exist.');
    }
    
}
