<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rute extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rute_model');
    } 

    /*
     * Listing of rute
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('rute/index?');
        $config['total_rows'] = $this->Rute_model->get_all_rute_count();
        $this->pagination->initialize($config);

        $data['rute'] = $this->Rute_model->get_all_rute($params);
        
        $data['_view'] = 'rute/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new rute
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required');
		$this->form_validation->set_rules('warna','Warna','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_rute' => $this->input->post('nama'),
				'warna' => $this->input->post('warna'),
            );
            
            $rute_id = $this->Rute_model->add_rute($params);
            redirect('rute/index');
        }
        else
        {            
            $data['_view'] = 'rute/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a rute
     */
    function edit($id)
    {   
        // check if the rute exists before trying to edit it
        $data['rute'] = $this->Rute_model->get_rute($id);
        
        if(isset($data['rute']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required');
			$this->form_validation->set_rules('warna','Warna','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_rute' => $this->input->post('nama'),
					'warna' => $this->input->post('warna'),
                );

                $this->Rute_model->update_rute($id,$params);            
                redirect('rute/index');
            }
            else
            {
                $data['_view'] = 'rute/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The rute you are trying to edit does not exist.');
    } 

    /*
     * Deleting rute
     */
    function remove($id)
    {
        $rute = $this->Rute_model->get_rute($id);

        // check if the rute exists before trying to delete it
        if(isset($rute['id']))
        {
            $this->Rute_model->delete_rute($id);
            redirect('rute/index');
        }
        else
            show_error('The rute you are trying to delete does not exist.');
    }
    
}
