<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Halte_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get halte by id
     */
    function get_halte($id)
    {
        return $this->db->get_where('dta_halte',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all halte count
     */
    function get_all_halte_count()
    {
        $this->db->from('dta_halte');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all halte
     */
    function get_all_halte($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('dta_halte')->result_array();
    }

    function get_all(){
        return  $this->db->get('dta_halte')->result_array();
    }
        
    /*
     * function to add new halte
     */
    function add_halte($params)
    {
        $this->db->insert('dta_halte',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update halte
     */
    function update_halte($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('dta_halte',$params);
    }
    
    /*
     * function to delete halte
     */
    function delete_halte($id)
    {
        return $this->db->delete('dta_halte',array('id'=>$id));
    }
}
