<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jalur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jalur by id
     */
    function get_jalur($id)
    {
        return $this->db->get_where('dtx_jalur',array('id'=>$id))->row_array();
    }

    function get_way_point($id_rute)
    {
        $sql="SELECT * FROM dtx_jalur inner join dta_rute on dtx_jalur.id_rute=dta_rute.id left join dta_halte on dtx_jalur.id_halte=dta_halte.id where dtx_jalur.id_rute=? and dtx_jalur.type=? ORDER BY dtx_jalur.urutan ASC";
        $query=$this->db->query($sql,array($id_rute,5));
        return $query->result_array();
    }

    function get_transit($id_rute)
    {
        $sql="SELECT * FROM dtx_jalur inner join dta_rute on dtx_jalur.id_rute=dta_rute.id left join dta_halte on dtx_jalur.id_halte=dta_halte.id where dtx_jalur.id_rute=? and dtx_jalur.type=? ORDER BY dtx_jalur.urutan ASC";
        $query=$this->db->query($sql,array($id_rute,4));
        return $query->result_array();
    }
    
    /*
     * Get all jalur count
     */
    function get_all_jalur_count()
    {
        $this->db->from('dtx_jalur');
        return $this->db->count_all_results();
    }

    function get_jalur_by_rute($id_rute){
        $sql="SELECT * FROM dtx_jalur inner join dta_rute on dtx_jalur.id_rute=dta_rute.id left join dta_halte on dtx_jalur.id_halte=dta_halte.id where dtx_jalur.id_rute=? ORDER BY dtx_jalur.urutan ASC";
        $query=$this->db->query($sql,$id_rute);
        return $query->result_array();
    }

    function get_halte_all(){
        $sql="SELECT * FROM dtx_jalur inner join dta_rute on dtx_jalur.id_rute=dta_rute.id left join dta_halte on dtx_jalur.id_halte=dta_halte.id ORDER BY dtx_jalur.urutan ASC";
        $query=$this->db->query($sql);
        return $query->result_array();
    }
        
    /*
     * Get all jalur
     */
    function get_all_jalur($params = array())
    {
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $sql="SELECT * FROM dtx_jalur inner join dta_rute on dtx_jalur.id_rute=dta_rute.id left join dta_halte on dtx_jalur.id_halte=dta_halte.id ORDER BY dtx_jalur.urutan ASC";
        $query=$this->db->query($sql);
        return $query->result_array();
    }
        
    /*
     * function to add new jalur
     */
    function add_jalur($params)
    {
        $this->db->insert('dtx_jalur',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jalur
     */
    function update_jalur($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('dtx_jalur',$params);
    }
    
    /*
     * function to delete jalur
     */
    function delete_jalur($id)
    {
        return $this->db->delete('dtx_jalur',array('id'=>$id));
    }
}
