<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rute_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rute by id
     */
    function get_rute($id)
    {
        return $this->db->get_where('dta_rute',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all rute count
     */
    function get_all_rute_count()
    {
        $this->db->from('dta_rute');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all rute
     */
    function get_all_rute($params = array())
    {
        $this->db->order_by('id', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('dta_rute')->result_array();
    }
        
    /*
     * function to add new rute
     */
    function add_rute($params)
    {
        $this->db->insert('dta_rute',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rute
     */
    function update_rute($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('dta_rute',$params);
    }
    
    /*
     * function to delete rute
     */
    function delete_rute($id)
    {
        return $this->db->delete('dta_rute',array('id'=>$id));
    }
}
